tasks:
  - type: dotnet-build
    auto:
      - source: push
    packages:
      - csproj: ./Haondt.Core/Haondt.Core.csproj
      - csproj: ./Haondt.Json/Haondt.Json.csproj
      - csproj: ./Haondt.Identity/Haondt.Identity.csproj
      - csproj: ./Haondt.Persistence/Haondt.Persistence.csproj
      - csproj: ./Haondt.Web.BulmaCSS/Haondt.Web.BulmaCSS.csproj
      - csproj: ./Haondt.Web/Haondt.Web.csproj
      - csproj: ./Haondt.Web.Core/Haondt.Web.Core.csproj
      - csproj: ./Haondt.Persistence.MongoDb/Haondt.Persistence.MongoDb.csproj
      - csproj: ./Haondt.Persistence.Postgresql/Haondt.Persistence.Postgresql.csproj
      - csproj: ./Haondt.Persistence.Sqlite/Haondt.Persistence.Sqlite.csproj
    registries:
      - gitlab
