<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

        <OutputType>Library</OutputType>

	  <IsPackable>true</IsPackable>
            <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>

      
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Haondt.Core\Haondt.Core.csproj" />
  </ItemGroup>


</Project>
